spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.168.100.223:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

logging:
  config: classpath:logback-spring.xml
server:
  port: 80
mybatis:
  type-aliases-package: com.un32.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

